// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnzYJ_UU89GoKwSoKeMjQGPvMkcP3790',
    appId: '1:975389749578:web:0335a7f077369c902491b3',
    messagingSenderId: '975389749578',
    projectId: 'sem7-8a59b',
    authDomain: 'sem7-8a59b.firebaseapp.com',
    storageBucket: 'sem7-8a59b.firebasestorage.app',
    measurementId: 'G-1ECYG6MTLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1iUcmRDt2VSGJXcmkEf2ZffqehFrLeU',
    appId: '1:975389749578:android:dafef8b2d43430322491b3',
    messagingSenderId: '975389749578',
    projectId: 'sem7-8a59b',
    storageBucket: 'sem7-8a59b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNGeDfm1p6P2K8jw4QiYCriusBc825uCA',
    appId: '1:975389749578:ios:4931e490f68932e32491b3',
    messagingSenderId: '975389749578',
    projectId: 'sem7-8a59b',
    storageBucket: 'sem7-8a59b.firebasestorage.app',
    androidClientId: '975389749578-p438gt384cs471g8ubor6kb6m7gbtfui.apps.googleusercontent.com',
    iosClientId: '975389749578-btea06e7k5ssgthaouolludb7l0r8e6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectSem7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNGeDfm1p6P2K8jw4QiYCriusBc825uCA',
    appId: '1:975389749578:ios:4931e490f68932e32491b3',
    messagingSenderId: '975389749578',
    projectId: 'sem7-8a59b',
    storageBucket: 'sem7-8a59b.firebasestorage.app',
    androidClientId: '975389749578-p438gt384cs471g8ubor6kb6m7gbtfui.apps.googleusercontent.com',
    iosClientId: '975389749578-btea06e7k5ssgthaouolludb7l0r8e6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectSem7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKnzYJ_UU89GoKwSoKeMjQGPvMkcP3790',
    appId: '1:975389749578:web:65ca8b196971aec92491b3',
    messagingSenderId: '975389749578',
    projectId: 'sem7-8a59b',
    authDomain: 'sem7-8a59b.firebaseapp.com',
    storageBucket: 'sem7-8a59b.firebasestorage.app',
    measurementId: 'G-XSMYH85HJQ',
  );
}
